apiVersion: v1
kind: Service
metadata:
  name: api

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: api
    release: "0"

  ports:
    - name: http
      port: 3000
      nodePort: 30081

  type: NodePort